general {
	layout = scrolling
}

plugin {
    hyprscrolling {
        fullscreen_on_one_column = true
    }
}

unbind = Super, BracketRight
unbind = Super, BracketLeft

# Focus columns
binde = Super, BracketRight, layoutmsg, focus r
binde = Super, BracketLeft, layoutmsg, focus l

# Swap columns
binde = Super+Shift, BracketRight, layoutmsg, swapcol r
binde = Super+Shift, BracketLeft, layoutmsg, swapcol l

# Promote new column
bind = Super, P, layoutmsg, promote

# Resize columns
binde = Super, Apostrophe, layoutmsg, colresize +conf
binde = Super, Semicolon, layoutmsg, colresize -conf