# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

##! Utilities
bind = Shift+Alt, E, exec, bemoji -n # Open Emote
bind = Super, V, exec, copyq show # Open CopyQ
bind = Alt, Space, exec, fuzzel # Fuzzel

## Screenshot
bind = Ctrl, Print, exec, hyprshot -m region -z # Screenshot region
bind = Ctrl+Shift, Print, exec, hyprshot -m output -m active # Screenshot active monitor
bind = Alt, Print, exec, hyprshot -m window -m active # Screenshot active window

##! Hyprexpo
bind = Super, P, hyprexpo:expo, toggle # Toggle Hyprexpo
