# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Desktop Gremlins
windowrule = no_blur on, no_shadow on, border_size 0, match:title ilgwg_desktop_gremlins.py

# VSCode
windowrule = opacity 0.9 override 0.95 override, match:class code

# Kitty
windowrule = opacity 0.9 override 0.95 override, match:class ^kitty$

# Pear
windowrule = opacity 0.85 override 0.95 override, match:class com.github.th_ch.youtube_music

# Vesktop
windowrule = workspace 2 silent, match:class vesktop

# Steam
windowrule = float on, match:class steam

# emote
windowrule = float on, match:class (emote|com.tomjwatson.Emote|Smile|it.mijorus.smile)

# copyq
windowrule = opacity 0.85 override 0.9, float on, move (cursor_x+(0)) (cursor_y+(0)), size 400 650, match:class com.github.hluk.copyq

# edex
windowrule = opacity 0.85 override 0.95, match:class eDEX-UI
