-- Generated by nwg-displays on 2026-06-18 at 14:26:31. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144.0",
    position = "1920x1080",
    scale = 1.0
})
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@165.01",
    position = "3840x1080",
    scale = 1.0
})
